all project
WaldemarKubiak/STW-PROJECT pull request #31
Opened 2022-12-18 18:14 UTC by simonprus

wszystko skończone czekam na bugi

2022-12-18 18:33 UTC, WaldemarKubiak requested changes
Zerknij na komentarze w liniach - zrób jeszcze raz przegląd i weryfikację kodu pod względem używania zmiennych - zamień html na czystą sekcję bez <!DOCTYPE html>
<html lang="en">
<head> itd. (1 do 10 liniii + 2 ostatnie w kodzie html)

2022-12-18 18:33 UTC, WaldemarKubiak commented on src/sass/_contacts.scss
> +@media (min-width: 1200px) {
zmień na 1280px (nasze punkty przerwania, to 480px, 768px i 1280px)

2022-12-18 18:33 UTC, WaldemarKubiak commented on src/partials/contacts.html
> +<body>
w html robimy tylko sekcje bez dodatków typu !DOCTYPE - zerknij na sekcje w innych html-ach

2022-12-18 18:33 UTC, WaldemarKubiak commented on src/partials/contacts.html
> +</html>
j.w. - sama sekcja

2022-12-18 18:33 UTC, WaldemarKubiak commented on src/sass/_contacts.scss
> +    list-style: none;
list-style: none jest w "modern-normalize.css" - zerknij czy będzie działało bez tego

2022-12-18 18:33 UTC, WaldemarKubiak commented on src/sass/_contacts.scss
> +        border-bottom: #E1E1E1 solid 1px;
zastosuj zmienną z _variables.scss ($grey-line)

2022-12-18 18:33 UTC, WaldemarKubiak commented on src/sass/_contacts.scss
> +        color: #907E82;
zastosuj zmienną z _variables

2022-12-18 21:22 UTC, SzymonCierpik approved these changes

2022-12-18 21:22 UTC, SzymonCierpik approved these changes

2022-12-19 21:03 UTC, SzymonCierpik approved these changes

2022-12-19 21:29 UTC, WaldemarKubiak requested changes
Poprawki

2022-12-19 21:30 UTC, WaldemarKubiak requested changes
Marginesy - poprawka

2022-12-19 23:17 UTC, closed without merging